openapi: 3.0.3
info:
  title: Example specification
  description: Example specification file
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /example/hello/{name}:
    get:
      description: |
        Test endpoint for testing which returns response as string
      tags:
        - "Example"
      operationId: hello
      parameters:
        - name: name
          in: path
          required: true
          allowEmptyValue: false
          schema:
            type: string
      responses:
        "200":
          description: Ok. Successful response returns string response
          content:
            application/json:
              schema:
                type: string
  /example/getCars:
    get:
      description: Test endpoint for getting list of cars
      tags:
        - "Example"
      operationId: getCars
      responses:
        "200":
          description: Ok. Successful response contains list of CarDto objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Car"
components:
  schemas:
    Car:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        productionYear:
          type: integer

