openapi: 3.0.3
info:
  title: Hello specification
  description: Hello specification
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /hello/{name}:
    get:
      description: |
        Endpoint for getting string response
      tags:
        - "Hello"
      operationId: sayHello
      parameters:
        - name: name
          in: path
          required: true
          allowEmptyValue: false
          schema:
            type: string
      responses:
        "200":
          description: Ok. Successful response contains string message.
          content:
            application/json:
              schema:
                type: string