openapi: 3.0.3
info:
  title: Plantation specification
  description: Plantation specification
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /plantation/create-plantation:
    description: |
      Endpoint for creating plantations
    post:
      tags:
        - "Plantation"
      operationId: createPlantation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Plantation"
      responses:
        "200":
          description: Ok. Successful response will return OK status.
  /plantation/edit-plantation:
    description: |
      Endpoint for editing existing plantations
    post:
      tags:
        - "Plantation"
      operationId: editPlantation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Plantation"
      responses:
        "200":
          description: Ok. Successful response will return OK status.
  /plantation/delete-plantation:
    description: |
      Endpoint for deleting existing plantations by given id
    post:
      tags:
        - "Plantation"
      operationId: deletePlantation
      parameters:
        - name: id
          in: query
          required: false
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Ok. Successful response will return OK status.
components:
  schemas:
    Plantation:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        nip:
          type: string
        regon:
          type: string
        city:
          type: string
        street:
          type: string
        houseNumber:
          type: integer
        flatNumber:
          type: integer
        postCode:
          type: string
        area:
          $ref: "#/components/schemas/Area"
        sectors:
          type: array
          items:
            $ref: "#/components/schemas/Area"
    Area:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        polygonColor:
          type: string
        coordinates:
          type: array
          items:
            $ref: "#/components/schemas/Coordinate"
    Coordinate:
      type: object
      properties:
        id:
          type: integer
          format: int64
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
