openapi: 3.0.3
info:
  title: UserHarvest specification
  description: UserHarvest specification
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /user-harvest/report-collected:
    description: |
      Endpoint for reporting collected container with fruits
    post:

