openapi: 3.0.3
info:
  title: Users specification file
  description: Users specification file
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /users/set-user-role:
    description: |
      Endpoint for setting user role. For example set new worker (ROLE_USER) as picker (ROLE_PICKER) or warehouseman 
      (ROLE_WAREHOUSEMAN).
    post:
      tags:
        - "Users"
      operationId: setUserRole
      parameters:
        - name: userId
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
        - name: role
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: string
      responses:
        "200":
          description: Ok. Successful response will return OK status and edited user id.
          content:
            application/json:
              schema:
                type: integer
                format: int64
  /users/search-employee-by-email:
    description: |
      Endpoint for finding people by email
    post:
      tags:
        - "Users"
      operationId: searchByEmail
      parameters:
        - name: searchPhrase
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: string
      responses:
        "200":
          description: Ok. Successful response will return OK status and list of matching users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Employee"
components:
  schemas:
    Employee:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
